version: "3"
services:
  node1:
    container_name: Node1
    image: java-docker
    networks:
      - db-app-1
      - servers-network
    depends_on:
      - mongo-1
    environment:
      DB_HOST: mongo-1
      DB_PORT: 27017
      MASTER: "yes"
      NODE_NO: 1
    ports: 
      - "8081:8080"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
  mongo-1:
    image: mongo
    networks:
      - db-app-1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-1:/data/db
  node2:
    container_name: Node2
    image: java-docker
    networks:
      - db-app-2
      - servers-network
    depends_on:
      - mongo-2
    environment:
      DB_HOST: mongo-2
      DB_PORT: 27017
      MASTER: "no"
      NODE_NO: 2
    ports: 
      - "8082:8080"
  mongo-2:
    image: mongo
    networks:
      - db-app-2
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-2:/data/db
  node3:
    container_name: Node3
    image: java-docker
    networks:
      - db-app-3
      - servers-network
    depends_on:
      - mongo-3
    environment:
      DB_HOST: mongo-3
      DB_PORT: 27017
      MASTER: "no"
      NODE_NO: 3
    ports: 
      - "8083:8080"
  mongo-3:
    image: mongo
    networks:
      - db-app-3
    ports:
      - "27019:27017"
    volumes:
      - mongo-data-3:/data/db
  controller:
    container_name: Controller
    build: Controller/.
    stdin_open: true
    networks:
      - servers-network
    depends_on:
      - node1
      - node2
      - node3
networks:
  db-app-1:
    driver: bridge
  db-app-2:
    driver: bridge
  db-app-3:
    driver: bridge
  servers-network:
    driver: bridge
volumes:
  mongo-data-1:
    driver: local
  mongo-data-2:
    driver: local
  mongo-data-3:
    driver: local
